### ISSUE TITLE
What's the ground-truth knowledge?

### ISSUE THREAD

**Issue by HUJA9** [DaoD/KPN#1]
Hello! I'm very interested in your brilliant work, but I was a little confused in some details. 

I noticed that there is no knowledge label in the original dataset, so how did you do to calculate the knowledge accuracy during the test period? And I couldn't find this calculation process in the code.

I was wondering if you measure the accuracy using the _weak label_ you propesed in the article? If yes, then how to ensure its credibility?

Looking forward to your reply
Best wishes :)

**Comment by DaoD** [comment]
Thanks for your attention on our work!

Yes, we use weak labels to calculate the accuracy. As we shown in the section of "Reliability of the Weak Labels", we randomly select 100 samples comprising 1,437 knowledge triplets from the validation set of DuConv, and ask three human annotators to label which triplet is necessary to select the current response. The result indicates that 90.26% of the generated labels are consistent with human annotations.

**Comment by HUJA9** [comment]
oh I see! Thanks for your help!
